name: CI CMS starter

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: cakes-management-system/ci-cd/.github/workflows/build-with-maven.yml@master
    with:
      display-name: Common Library
      sonar: true
      sonar-project-key: cakes-management-system_cms-starter
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
